version: '3.8'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'   # HTTP
      - '81:81'   # Admin interface
      - '443:443' # HTTPS
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - contract-net

  contract-app:
    image: sarangcr03/nonsalant-contract:latest
    restart: unless-stopped
    networks:
      - contract-net

networks:
  contract-net:
    driver: bridge
